name: Generate Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: ["main", "master"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Cartão 1: Cima Esquerda (Visão Geral de Commits e Atividade)
      - name: Top Left - Overview Stats
        uses: lowlighter/metrics@latest
        with:
          filename: metrics-top-left.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: RaffaGR
          template: classic
          base: activity, community
          config_theme: tokyonight

      # Cartão 2: Cima Direita (Linguagens Mais Usadas)
      - name: Top Right - Languages
        uses: lowlighter/metrics@latest
        with:
          filename: metrics-top-right.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: RaffaGR
          template: classic
          base: ""
          config_theme: tokyonight
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_colors: github
          plugin_languages_limit: 8

      # Cartão 3: Embaixo (Gráfico Isométrico de Contribuições cobrindo a largura)
      # - name: Bottom - Isocalendar
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: metrics-bottom.svg
      #     token: ${{ secrets.METRICS_TOKEN }}
      #     user: RaffaGR
      #     template: classic
      #     base: ""
      #     config_theme: tokyonight
      #     plugin_isocalendar: yes
      #     plugin_isocalendar_duration: full-year

      # Cartão 3: Embaixo (Calendário 3D)
      # - name: Bottom - Isocalendar
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: metrics-bottom.svg
      #     token: ${{ secrets.METRICS_TOKEN }}
      #     user: RaffaGR
      #     template: classic
      #     base: ""
      #     config_theme: tokyonight
      #     plugin_isocalendar: yes
      #     plugin_isocalendar_duration: full-year

      # Cartão 3: Embaixo (Performance e Auditoria do Portfólio)
      # - name: Bottom - PageSpeed
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: metrics-bottom.svg
      #     token: ${{ secrets.METRICS_TOKEN }}
      #     user: RaffaGR
      #     template: classic
      #     base: ""
      #     config_theme: tokyonight
      #     plugin_pagespeed: yes
      #     plugin_pagespeed_url: https://rafa-dev-atomic.vercel.app/ 
      #     plugin_pagespeed_detailed: yes

      # Cartão 3: Calendário 2D Clean
      # - name: Bottom - Full Calendar
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: metrics-bottom.svg
      #     token: ${{ secrets.METRICS_TOKEN }}
      #     user: RaffaGR
      #     template: classic
      #     base: ""
      #     config_theme: tokyonight
      #     plugin_calendar: yes
      #     plugin_calendar_limit: 1

      # Cartão 3: Embaixo (Gráfico de Ondas de Atividade)
      # - name: Bottom - Activity Graph
      #   uses: maurodesouza/github-readme-activity-graph-action@v1
      #   with:
      #     username: RaffaGR
      #     theme: tokyonight
      #     area: true
      #     hide_border: true
      #     output_path: metrics-bottom.svg
      #     token: ${{ secrets.METRICS_TOKEN }}

      # Cartão 3: Embaixo (Gráfico de Ondas Verde - Tema github-compact)
      - name: Bottom - Activity Graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: RaffaGR
          theme: github-compact
          area: true
          hide_border: true
          output_path: metrics-bottom.svg
          token: ${{ secrets.METRICS_TOKEN }}
      - name: Push metrics-bottom.svg to repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add metrics-bottom.svg
          git commit -m "Update metrics-bottom.svg" || exit 0
          git push
